dependencies:
- name: mongodb
  version: 7.14.8
  repository: https://charts.bitnami.com/bitnami
  condition: mongodb.enabled

- name: rabbitmq
  version: 8.26.3
  repository: https://charts.bitnami.com/bitnami
  condition: rabbitmq.enabled

- name: postgresql
  version: 10.16.1
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
