apiVersion: v1
kind: Secret
metadata:
  name: {{ include "full_name" . }}-postgres-secret
  labels:
{{ include "chart_labels" . | indent 4 }}
type: Opaque
stringData:
  USER: {{ .Values.secrets.coog.postgres.user | quote }}
  PASSWORD: {{ .Values.secrets.coog.postgres.password | quote }}
