{{- if .Values.coog.enabled -}}
{{- if .Values.coog.ingress.enabled -}}
{{- $fullName := include "full_name" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "chart_labels" . | indent 4 }}
  {{- with .Values.coog.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.coog.ingress.tls }}
  tls:
  {{- range .Values.coog.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.coog.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
        - path: {{ . }}
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}
              port:
                name: http
        {{- end }}
  {{- end }}
{{- end }}
{{- end }}
