{{- if .Values.gateway.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "full_name" . }}-mongo-db-secret
  labels:
{{ include "chart_labels" . | indent 4 }}
type: Opaque
stringData:
  USER: {{ .Values.secrets.gateway.mongodb_user | quote }}
  PASSWORD: {{ .Values.secrets.gateway.mongodb_root_password | quote }}
{{- end }}
